spring:
  application:
    name: aec-prod
  docker:
    compose:
      enabled: false
  cloud:
    compatibility-verifier:
      enabled: false
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  # Configuración de la base de datos
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  accessMs: ${JWT_ACCESS_MS:3600000}
  refreshMs: ${JWT_REFRESH_MS:86400000}

file-service:
  base-url: ${FILE_SERVICE_BASE_URL:http://file-service.railway.internal:8084}

gateway:
  public-base-url: ${GATEWAY_PUBLIC_BASE_URL:https://gateway-production-129e.up.railway.app}

users:
  service:
    url: ${USERS_SERVICE_URL:http://users-service.railway.internal:8081/api/users}

file:
  upload-dir: ${UPLOAD_DIR:/app/uploads}

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.aec.prodsrv: DEBUG
    # Agrega logging específico para Feign si usas OpenFeign
    org.springframework.cloud.openfeign: DEBUG