spring:
  application:
    name: aec-product
  datasource:
    url:      ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/aec}
    username: ${DATASOURCE_USER:aec}
    password: ${DATASOURCE_PASS:2412}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create}

server:
  port: ${SERVER_PORT:8083}

spring:
  servlet:
    multipart:
      max-file-size:        200MB
      max-request-size:     200MB

file-service:
  base-url: ${FILE_SVC_URL:http://localhost:8084}

users-service:
  url: ${USERS_SVC_URL:http://localhost:8081/api/users}

spring:
  cloud:
    compatibility-verifier:
      enabled: false

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
